on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          comment-template: |
            🚀 Released in {release_link}.
